<div class="row-fluid" style="margin-top:46px; margin-right:20px; margin-left:20px;">
  <div class="span12">
    <h3>Repo Request Form</h3>
  </div>
</div>

<div class="row-fluid" style="margin-top:20px;">
<div class="span12" style="padding:6px;">
<ol class="progtrckr" data-progtrckr-steps="5">
    <li class="progtrckr-done">Status</li><!--
 --><li class="progtrckr-done">Details</li><!--
 --><li class="progtrckr-done">Instructions</li><!--
 --><li class="progtrckr-done">Requirements</li><!--
 --><li class="progtrckr-todo">Acknowlegement</li>
</ol>
</div>
</div>


<div class="row-fluid" style="margin-top:28px; border-bottom: 1px solid #eeeeee;">
  <div class="span4">What are your system requirements?</div>
  <div class="span4 offset4" id="flashmessage" style="text-decoration:italic;"></div>
</div>

<a onclick="addRequirementAction();"
					class="sp-button sp-button-icon-left ui-state-default ui-corner-all" style="margin-top:16px; margin-bottom:11px;"><span
					class="ui-icon ui-icon-circle-plus"></span>Create a requirement</a>
					
<div class="row-fluid" style="margin-top:6px; margin-bottom:10px; height:250px;">
  <div class="span12">
    <div class="row-fluid">
      <div class="span6" id="requirements-section">
      <div class="row-fluid">
      <?php foreach($models as $model):?>
          <input type="hidden" maxlength="10" id="readme-value"value="<?php echo $model->id; ?>"/>
          <input type="hidden" maxlength="60" id="readme-count" value="<?php echo count($model->requirements); ?>"/>
      <?php $i = 0; ?>
      <?php foreach($model->requirements as $requirement):?>
      
      <div class="row-fluid" id="requirements-section-row-<?php echo $i; ?>">
          <div class="span6" style="margin-top:6px; margin-bottom: 6px;">
          	<input type="text" maxlength="60" id="requirements-<?php echo $i; ?>" value="<?php echo $requirement ?>"/>
          </div>
          <div class="span6" style="margin-top:6px; margin-bottom: 6px;">
          	<span onclick="removeRequirementAction(this);" class="ui-icon ui-icon-closethick" id="remove-<?php echo $i; ?>"></span>
          </div>
          </div>
          <?php $i = $i + 1; ?>
          <?php endforeach;?>
       <?php endforeach; ?>
        </div>
      </div>
      <div class="span6"><div style="margin-top: 20px; margin-left:8px; margin-right:8px;">Live content...</div></div>
    </div>
  </div>
</div>


<div class="row-fluid" style="margin-top:28px;">
<div style="display: block; height:2px; margin-top:8px; border-top:2px solid #eeeeee;"></div>
  <div class="span12 offset8" style="margin-top:10px;">
  <a onclick="addRequirementAction();"
					class="sp-button sp-button-icon-left ui-state-default ui-corner-all" style="margin-top:6px;"><span
					class="ui-icon ui-icon-seek-next"></span>Next</a>
  </div>
</div>
