<div class="row-fluid" style="margin-top:46px; margin-right:20px; margin-left:20px;">
  <div class="span12">
    <h3>Repo Request Form</h3>
  </div>
</div>

<div class="row-fluid" style="margin-top:20px;">
<div class="span12" style="padding:6px;">
<ol class="progtrckr" data-progtrckr-steps="5">
    <li class="progtrckr-done">Status</li><!--
 --><li class="progtrckr-todo">Details</li><!--
 --><li class="progtrckr-todo">Instructions</li><!--
 --><li class="progtrckr-todo">Requirements</li><!--
 --><li class="progtrckr-todo">Acknowlegement</li>
</ol>
</div>
</div>


<div class="row-fluid" style="margin-top:28px; border-bottom: 1px solid #eeeeee;">
  <div class="span4">Will this repository be public or private?</div>
  <div class="span4 offset4" id="flashmessage" style="text-decoration:italic;"></div>
</div>
					
<div class="row-fluid" style="margin-top:6px; margin-bottom:10px; height:250px;">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12" id="status-section">
      <div class="row-fluid">
          <input type="hidden" maxlength="10" id="readme-value"value="<?php echo $models->id; ?>"/> 
      <div class="row-fluid" id="status-section-row">
      <p>This is the sess val: <?php echo $models->sess; ?></p>
          <div class="span12" id="radio-jquery-ui">
          <?php if ($models->type == "Public"):?>
  			<input id="Public" name="radio" type="radio" checked="checked"/><label style="display:inline; vertical-align: middle; margin-left:10px;">Public</label>
  			<input id="Private" name="radio" type="radio" style="margin-left:20px;"/><label style="display:inline; vertical-align: middle; margin-left:10px;">Private</label>
  			<?php endif; ?>
  			
  			<?php if ($models->type == "Private"):?>
  			<input id="Public" name="radio" type="radio" /><label style="display:inline; vertical-align: middle; margin-left:10px;" for="radio1">Public</label>
  			<input id="Private" name="radio" type="radio" checked="checked" style="margin-left:20px;"/><label style="display:inline; vertical-align: middle; margin-left:10px;" for="radio1">Private</label>
  			<?php endif; ?>
  			
  			<?php if ($models->type == ""):?>
  			<input id="Public" name="radio" type="radio" /><label for="radio1" style="display:inline; vertical-align: middle; margin-left:10px;">Public</label>
  			<input id="Private" name="radio" type="radio" style="margin-left:20px;"/><label for="radio1" style="display:inline; vertical-align: middle; margin-left:10px;">Private</label>
  			<?php endif; ?>
			</div>
          </div>
          
          <div class="row-fluid" style="margin-top:28px; border-bottom: 1px solid #eeeeee;">
  <div class="span4">The repository status is:</div>
</div>

<div class="row-fluid" style="margin-top:6px; margin-bottom:10px; height:250px;">
<?php if ($models->status == "Pending"):?>
  <div class="span12"><span style="color:#FFA500; font-weight:bold;"><?php echo $models->status;?></span></div>
  <?php endif; ?>
  
  <?php if ($models->status == "Created"):?>
  <div class="span12"><span style="color:yellowgreen; font-weight:bold;"><?php echo $models->status;?></span></div>
  <?php endif; ?>
  
  </div>

        </div>
      </div>
    </div>
  </div>
</div>


<div class="row-fluid" style="margin-top:28px;">
<div style="display: block; height:2px; margin-top:8px; border-top:2px solid #eeeeee;"></div>
  <div class="span12 offset8" style="margin-top:10px;">
  <a onclick="addRequirementAction();"
					class="sp-button sp-button-icon-left ui-state-default ui-corner-all" style="margin-top:6px;"><span
					class="ui-icon ui-icon-seek-next"></span>Next</a>
  </div>
</div>
