<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/redmond/jquery-ui-1.9.2.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-1.8.3.js')
                                      ->appendFile($this->basePath() . '/js/jquery-ui-1.9.2.custom.min.js')
        							  ->appendFile($this->basePath() . '/js/custom.js') ?>

    </head>
    <body>
        <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container" style="margin-left:0px;">
      <!-- 
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
       -->

      <div> <!-- class="nav-collapse" -->
      <div style="display: inline;">
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
            </ul>
          </li>
        </ul>
        </div>
        <!--   <div style="display: block; margin-left:222px; border-radius: 15px; width:210px; height:70px; border-right-style:solid; border-left-style:solid; border-bottom-style:solid; border-width:1px;"> -->
              <ul class="icon-area">
      <li class="icon-area"><a class="brand-github" href="#" style="display:block; height:60px;"></a></li>
      <li class="icon-area"><a class="brand-separator" href="#" style="display:block; height:60px;"></a></li>
      <li class="icon-area"><a class="brand-esri" href="#" style="display:block; height:60px;"></a></li>
      </ul>
      <!--  </div> -->
        <div class="pull-right navbar-text">
  <img src="http://placehold.it/30x30">
  Chuck Norris
</div>
        <!--  <form class="navbar-search pull-right" action="">
          <input type="text" class="search-query span2" placeholder="Search">
        </form> -->
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
