<div class="grid4" style="opacity: 0;">
	<div class="dark box">
		<div class="content">
			<div class="hack_small" id="unicorn-expedition">
				<a
					href="/hackathons/foursquare-hackathon-2013/hacks/unicorn-expedition"
					class="media screenshot"><img alt="Original"
					src="https://s3.amazonaws.com/hackerleague/hacks/screenshots/50e8d91e8485e702000000a0/original.png?1357442258"></a>
				<div class="title">
					<h2 class="inline">
						<a
							href="/hackathons/foursquare-hackathon-2013/hacks/unicorn-expedition"
							class="invert">unicorn expedition</a>
					</h2>
					<p class="sub">
						<a href="/hackathons/foursquare-hackathon-2013" class="invert">Foursquare
							Hackathon 2013</a>
					</p>
				</div>
				<h2>Sometimes what your heart desires just can't be found.</h2>

				<p>
					<img
						src="http://normalfornorfolkblog...%20[read%20more]%28/hackathons/foursquare-hackathon-2013/hacks/unicorn-expedition"
						alt="Alt text"><br>
				</p>

				<hr>
				<h4>Team</h4>
				<div class="gallery users">
					<div class="user">
						<a href="/users/mjording" class=" media inline float_left"><img
							alt="C41e290068fd34eb264bbd76e6484220?s=60&amp;d=retro"
							class="avatar"
							src="https://secure.gravatar.com/avatar/c41e290068fd34eb264bbd76e6484220?s=60&amp;d=retro"></a>
						<div class="details">
							<a href="/users/mjording" class="username">mjording</a> <br>
							<div class="muted">Matthew Jording</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>